import './globals.css';
import { appWithTranslation } from 'next-i18next';
import Header from '@/components/common/Header';
import Footer from '@/components/common/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}

export default appWithTranslation(RootLayout);
